/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    Ai: typeof import('./src/components/mains/main-page/content/content-page/Ai.vue')['default']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AmendButton: typeof import('./src/components/mains/main-page/content/content-page/AmendButton.vue')['default']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    Content: typeof import('./src/components/mains/main-page/content/Content.vue')['default']
    Intention: typeof import('./src/components/mains/main-page/content/content-page/Intention.vue')['default']
    MultilevelHeading: typeof import('./src/components/mains/main-page/content/content-page/MultilevelHeading.vue')['default']
    PersonalInfor: typeof import('./src/components/mains/main-page/content/content-page/PersonalInfor.vue')['default']
    PersonalInformation: typeof import('./src/components/mains/main-page/PersonalInformation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderLogo: typeof import('./src/components/mains/main-page/SiderLogo.vue')['default']
    Time: typeof import('./src/components/mains/main-page/content/content-page/Time.vue')['default']
    User: typeof import('./src/components/mains/main-page/content/content-page/User.vue')['default']
    VoiceButton: typeof import('./src/components/mains/main-page/content/content-page/VoiceButton.vue')['default']
    VoiceInput: typeof import('./src/components/mains/main-page/footer/VoiceInput.vue')['default']
    VoiceWave: typeof import('./src/components/mains/main-page/footer/VoiceWave.vue')['default']
  }
}
