/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    Ai: typeof import('./src/components/mains/main-page/content/content-page/Ai.vue')['default']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    Content: typeof import('./src/components/mains/main-page/content/Content.vue')['default']
    PersonalInformation: typeof import('./src/components/mains/main-page/PersonalInformation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiderLogo: typeof import('./src/components/mains/main-page/SiderLogo.vue')['default']
    Time: typeof import('./src/components/mains/main-page/content/content-page/Time.vue')['default']
    User: typeof import('./src/components/mains/main-page/content/content-page/User.vue')['default']
    VoiceButton: typeof import('./src/components/mains/main-page/content/content-page/VoiceButton.vue')['default']
    VoiceInput: typeof import('./src/components/mains/main-page/footer/VoiceInput.vue')['default']
    VoiceWave: typeof import('./src/components/mains/main-page/footer/VoiceWave.vue')['default']
  }
}
